name: GitHub Actions Unwanted File Check
on: [push]
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Fail if intervention is needed
        run: |
          if [[ -f "unwantedFile" ]]; then
              echo unwantedFile exists. >> $GITHUB_STEP_SUMMARY
              exit 1
          else
              echo unwantedFile does not exist. >> $GITHUB_STEP_SUMMARY
          fi
