name: GitHub Actions Unwanted File Check
on: [pull_request]
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Fail if intervention is needed
        run: |
          if [[ -f "unwantedFile.go" ]]; then
              echo unwantedFile.go exists. >> $GITHUB_STEP_SUMMARY
              exit 1
          else
              echo unwantedFile.go does not exist. >> $GITHUB_STEP_SUMMARY
          fi
